- params:
    git:
      repoName: jenkins-jfrog-plugin
      branches:
        - main
    scan:
      projects:
        - repository: cli-mvn-remote-1673961361
          installCommand: "mvn compile -X -e"